version: "3.3"
services:
  app:
    image: node:18-alpine
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
